/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void start_click(GButton source, GEvent event) { //_CODE_:start:783324:
  makecard();
} //_CODE_:start:783324:

public void next_click(GButton source, GEvent event) { //_CODE_:next:685857:
  if (currentcard != numcard - 1)
    currentcard += 1;
} //_CODE_:next:685857:

public void previous_click(GButton source, GEvent event) { //_CODE_:previous:940897:
  if (currentcard != 0)
    currentcard -= 1;
} //_CODE_:previous:940897:

public void Remove_click(GButton source, GEvent event) { //_CODE_:Remove:730698:
  user_Cards.remove(currentcard);
  numcard -= 1;
  if (currentcard != 0)
    currentcard -= 1;
  else
    currentcard = 0;
} //_CODE_:Remove:730698:

public void Add_click(GButton source, GEvent event) { //_CODE_:Add:490421:
  numcard += 1;
} //_CODE_:Add:490421:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  start = new GButton(this, 250, 340, 80, 30);
  start.setText("Start");
  start.addEventHandler(this, "start_click");
  next = new GButton(this, 400, 560, 80, 30);
  next.setText("Next");
  next.addEventHandler(this, "next_click");
  previous = new GButton(this, 300, 560, 80, 30);
  previous.setText("Previous");
  previous.addEventHandler(this, "previous_click");
  Remove = new GButton(this, 200, 560, 80, 30);
  Remove.setText("Remove Card");
  Remove.addEventHandler(this, "Remove_click");
  Add = new GButton(this, 100, 560, 80, 30);
  Add.setText("Add Card");
  Add.addEventHandler(this, "Add_click");
}

// Variable declarations 
// autogenerated do not edit
GButton start; 
GButton next; 
GButton previous; 
GButton Remove; 
GButton Add; 
